name: Basic Commands 
on:
   push:
      branches:
         - main 
    

jobs:
  demo-commands1:
    runs-on: ubuntu-latest

    steps:
       - name: show current working directory 
         run: pwd

    
