name: Run Java and Python Programs

on:
  push:
    branches:
      - main
  

jobs:
  run-all:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Java 17
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

    
     

