name: Run python and java programs 
on:
   push:
      branches:
         - main 

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout code
         uses: actions/checkout@v4
       
       - name: Set up Java 
         uses: actions/setup-java@v4
         with:
           distribution: 'temurin'
           java-version: '17'

       - name: Compile java program
         run: java programOne.java programTwo.java

       - name: run programOne
         run: java programOne

       - name: run programTwo 
         run: java programTwo 
         
       - name: Set up Python 
         uses: actions/setup-python@v5
         with:
          python-version: '3.10'

       - name: Run python.py
         run: python python.py
